import redirectToSignIn from '@libs/actions/SignInRedirect';
import * as NetworkStore from '@libs/Network/NetworkStore';
import reauthenticate from '@libs/Reauthentication';
import waitForBatchedUpdates from '../../utils/waitForBatchedUpdates';

jest.mock('@src/libs/Log');

jest.mock('@src/libs/actions/SignInRedirect', () => ({
    __esModule: true,
    default: jest.fn().mockResolvedValue(undefined),
}));

jest.mock('@src/libs/Network/NetworkStore', () => ({
    getCredentials: jest.fn(),
    hasReadRequiredDataFromStorage: jest.fn(),
    setIsAuthenticating: jest.fn(),
    setAuthToken: jest.fn(),
    getAuthToken: jest.fn(),
    checkRequiredData: jest.fn(),
    resetHasReadRequiredDataFromStorage: jest.fn(),
}));

jest.mock('@src/libs/SessionUtils', () => ({
    checkIfShouldUseNewPartnerName: jest.fn().mockReturnValue(true),
}));

jest.mock('@src/libs/telemetry/trackAuthenticationError', () => ({
    __esModule: true,
    default: jest.fn(),
}));

const mockRedirectToSignIn = redirectToSignIn as jest.Mock;
const mockGetCredentials = NetworkStore.getCredentials as jest.Mock;
const mockHasReadRequiredDataFromStorage = NetworkStore.hasReadRequiredDataFromStorage as jest.Mock;
const mockSetIsAuthenticating = NetworkStore.setIsAuthenticating as jest.Mock;

beforeEach(() => {
    jest.clearAllMocks();
    mockHasReadRequiredDataFromStorage.mockResolvedValue(undefined);
});

describe('reauthenticate', () => {
    describe('when credentials are missing', () => {
        it('redirects to sign in when credentials are null', async () => {
            mockGetCredentials.mockReturnValue(null);

            const result = await reauthenticate('TestCommand');
            await waitForBatchedUpdates();

            expect(mockRedirectToSignIn).toHaveBeenCalledWith('No credentials available');
            expect(result).toBe(false);
        });

        it('redirects to sign in when credentials are empty object', async () => {
            mockGetCredentials.mockReturnValue({});

            const result = await reauthenticate('TestCommand');
            await waitForBatchedUpdates();

            expect(mockRedirectToSignIn).toHaveBeenCalledWith('No credentials available');
            expect(result).toBe(false);
        });

        it('redirects to sign in when only autoGeneratedLogin is present', async () => {
            mockGetCredentials.mockReturnValue({autoGeneratedLogin: 'test-login'});

            const result = await reauthenticate('TestCommand');
            await waitForBatchedUpdates();

            expect(mockRedirectToSignIn).toHaveBeenCalledWith('No credentials available');
            expect(result).toBe(false);
        });

        it('redirects to sign in when only autoGeneratedPassword is present', async () => {
            mockGetCredentials.mockReturnValue({autoGeneratedPassword: 'test-password'});

            const result = await reauthenticate('TestCommand');
            await waitForBatchedUpdates();

            expect(mockRedirectToSignIn).toHaveBeenCalledWith('No credentials available');
            expect(result).toBe(false);
        });

        it('stops the authenticating state before redirecting', async () => {
            mockGetCredentials.mockReturnValue(null);

            await reauthenticate('TestCommand');
            await waitForBatchedUpdates();

            // setIsAuthenticating(false) should be called to release the network pause
            expect(mockSetIsAuthenticating).toHaveBeenCalledWith(false);
        });
    });
});
